# Generated by Django 3.1.4 on 2020-12-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=15)),
                ('exec_time', models.DateTimeField(max_length=20)),
                ('info', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Page1',
                'verbose_name_plural': '页面1',
            },
        ),
    ]
